### ISSUE TITLE
how to convert model weights(e.g., bigscience/bloomz-560m-optimizer-states) to Hugging Face model.bin file?

### ISSUE THREAD

**Issue by qazwsx042** [bigscience-workshop/xmtf#16]
Hi, how to convert model weights(e.g., bigscience/bloomz-560m-optimizer-states) to Hugging Face model.bin file?

**Comment by Muennighoff** [comment]
You can use this script: `https://github.com/huggingface/transformers/blob/main/src/transformers/models/bloom/convert_bloom_original_checkpoint_to_pytorch.py`

E.g.

`python convert_bloom_original_checkpoint_to_pytorch.py --bloom_checkpoint_path bloomz-560m-optimizer-states --pytorch_dump_folder_path ./ --pretraining_tp 1`

**Comment by qazwsx042** [comment]
>

**Comment by qazwsx042** [comment]
@Muennighoff Thanks!
