### ISSUE TITLE
Dose mt0&bloomz trained on dev, devtest datasets of Flores-200?

### ISSUE THREAD

**Issue by dsj96** [bigscience-workshop/xmtf#22]
According to [link](https://github.com/facebookresearch/flores/blob/main/flores200/README.md), Florse-200 only has dev, devtest sets. 
So, if I want to evaluate the translation performance of mt0&bloomz, It is unreasonable to evaluate on the Florse-200 **dev**, **devtest** datasets directly.

Do I understand correctly？
![1695813250778](https://github.com/bigscience-workshop/xmtf/assets/51779172/732f5360-0677-4bc6-9445-9026003833a7)

**Comment by Muennighoff** [comment]
Yeah we train on both so it does not make a lot of sense to evaluate on flores; We generally train on all splits for yellow datasets

**Comment by dsj96** [comment]
Thank you very much for your quickly reply.
