### ISSUE TITLE
Some datasets are not in xP3all

### ISSUE THREAD

**Issue by mkw18** [bigscience-workshop/xmtf#5]
Hello! It seems that some datasets like xnli and xwinogrande-ru are not in xP3all in huggingface. I wonder if they would be uploaded later? Thank you!

**Comment by Muennighoff** [comment]
Hey the reason that `xwinogrande-ru` is not in xP3all is because Russian is excluded, i.e. it's only the BLOOM languages.
All NLI datasets (RTE, XNLI etc) are excluded from xP3all

**Comment by mkw18** [comment]
Thank you! I'm also interested in this topic so I just what to try to implement. I read in your paper that NLI datasets are parts of test datasets, why are they excluded from xP3all? And I also didn't find xstory_cloze in xP3all, how could I download the whole testing dataset?

**Comment by Muennighoff** [comment]
The reason they're included was that we wanted to keep them for valuation even after training on xP3all, but you may as well include them.

For xstory_cloze you need to contact the authors of the XGLM paper, as it is not a publicly released dataset unfortunately.

**Comment by mkw18** [comment]
I see, I will contact them for the dataset. Thanks a lot for your reply!
